"""created tokens

Revision ID: fce0659cd154
Revises: 
Create Date: 2021-11-05 15:14:19.449705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce0659cd154'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('employee', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_employee_token'), 'employee', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_token'), table_name='employee')
    op.drop_column('employee', 'token_expiration')
    op.drop_column('employee', 'token')
    # ### end Alembic commands ###
